server:
    assets-path: /app/assets

theme:
    # Note: assets are cached by the browser, changes to the CSS file
    # will not be reflected until the browser cache is cleared (Ctrl+F5)
    custom-css-file: /assets/user.css
    # Tucan
    background-color: 50 10 17
    primary-color: 24 97 58
    negative-color: 56.8 58.2 1
    presets:
        gruvbox-dark:
            background-color: 0 0 16
            primary-color: 43 59 81
            positive-color: 61 66 44
            negative-color: 6 96 59
        zebra:
            light: true
            background-color: 0 0 95
            primary-color: 0 0 10
            negative-color: 0 90 50

pages:
    - $include: page-home.yml
    - $include: page-start-page.yml

