# 在 pages 區塊中添加這個新 page
- name: Services
  columns:
      - size: full
        widgets:
            - type: html
              source: |
                  <iframe src="http://localhost:8080" width="100%" height="800px" allowTransparency="true" frameborder="0"></iframe>

