- name: Start Page
  columns:
      - size: small
        widgets:
            - $include: widget/widget-word-of-the-day.yml
            - type: bookmarks
              groups:
                  - title: Quick Links
                    links:
                        - title: YouTube
                          url: https://www.youtube.com/
                          icon: di:youtube
                        - title: Twitch
                          url: https://www.twitch.tv/
                          icon: di:twitch
                        - title: Gmail
                          url: https://mail.google.com/mail/u/0/
                          icon: di:gmail
                        - title: Google Maps
                          url: https://www.google.com/maps
                          icon: di:google-maps
                        - title: Google Calendar
                          url: https://calendar.google.com/calendar/u/0/r
                          icon: di:google-calendar
                        - title: Perplexity
                          url: https://www.perplexity.ai/
                          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/perplexity-dark.svg
                        - title: Claude
                          url: https://claude.ai/
                          icon: di:claude-ai
                  - title: Entertainment
                    color: 10 70 50
                    links:
                        - title: YouTube
                          url: https://www.youtube.com/
                          icon: di:youtube
                        - title: Reddit
                          url: https://www.reddit.com/
                          icon: di:reddit
                        - title: Hyread
                          url: https://ebook.hyread.com.tw/
                        - title: Geocache
                          url: https://www.geocaching.com/play/search
                  - title: Work
                    color: 86 75 60
                    links:
                        - title: Github Repos
                          url: https://github.com/kevinshu1995?tab=repositories
                          icon: di:github-light
                        - title: Cloudflare
                          url: https://www.cloudflare.com/
                          icon: di:cloudflare
                        - title: Zeabur
                          url: https://zeabur.com/projects
                          icon: https://unpkg.com/@lobehub/icons-static-svg@latest/icons/zeabur.svg
                        - title: Vercel
                          url: https://vercel.com/login
                  - title: Study
                    color: 200 50 50
                    links:
                        - title: Spanish Dictionary
                          url: https://www.spanishdict.com/
                        - title: English News in Levels
                          url: https://englishnewsinlevels.com/
                        - title: Frontend Masters
                          url: https://frontendmasters.com/
                        - title: Vue Mastery
                          url: https://www.vuemastery.com/courses/
      - size: full
        widgets:
            - type: search
              search-engine: google
              autofocus: true
              target: _self
              bangs:
                  - title: YouTube
                    shortcut: "!yt"
                    url: https://www.youtube.com/results?search_query={QUERY}
                  - title: YouTube
                    shortcut: "!pp"
                    url: https://www.perplexity.ai/search?q={QUERY}
            - type: group
              widgets:
                  - type: hacker-news
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                  - type: rss
                    title: News
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://news.pts.org.tw/xml/newsfeed.xml
                          title: 公視
                        - url: https://feeds.feedburner.com/rsscna/intworld
                          title: 中央通訊社 | 國際
                        - url: https://feeds.feedburner.com/rsscna/technology
                          title: 中央通訊社 | 科技
                        - url: https://feeds.feedburner.com/rsscna/sport
                          title: 中央通訊社 | 體育
                        - url: https://www.twreporter.org/a/rss2.xml
                          title: 報導者
                  - type: rss
                    title: English News
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://feeds.bbci.co.uk/news/world/rss.xml
                          title: BBC News | World
                        - url: https://feeds.bbci.co.uk/news/rss.xml
                          title: BBC News | Top Stories
                  - type: rss
                    title: Games
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://www.4gamers.com.tw/rss/latest-news
                          title: 4gamers
                        - url: https://gnn.gamer.com.tw/rss.xml
                          title: 巴哈姆特 GNN 新聞網
                        - url: https://store.steampowered.com/feeds/news.xml
                          title: steam news
                  - type: rss
                    title: Tech
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://web.dev/static/blog/feed.xml
                          title: web.dev
                        - url: https://dev.to/feed
                          title: dev.to
                        - url: https://www.freecodecamp.org/news/rss
                          title: freeCodeCamp
                        - url: https://css-tricks.com/feed/
                          title: css-tricks
            - $include: widget/widget-raindrop.yml
      - size: small
        widgets:
            - type: clock
              hour-format: 24h
              timezones:
                  - timezone: Europe/Paris
                    label: Paris
                  - timezone: America/New_York
                    label: New York

            - type: calendar
              first-day-of-week: monday

            - type: weather
              location: Taipei, Taiwan
              units: metric
              hour-format: 12h

