- name: Start Page
  columns:
      - size: small
        widgets:
            - $include: widget/widget-word-of-the-day.yml
      - size: full
        widgets:
            - type: search
              search-engine: google
              autofocus: true
              target: _self
              bangs:
                  - title: YouTube
                    shortcut: "!yt"
                    url: https://www.youtube.com/results?search_query={QUERY}
                  - title: YouTube
                    shortcut: "!pp"
                    url: https://www.perplexity.ai/search?q={QUERY}
            - $include: widget/raindrop-bookmarks/raindrop-bookmarks.yml
      - size: small
        widgets:
            - type: clock
              hour-format: 24h
              timezones:
                  - timezone: Europe/Paris
                    label: Paris
                  - timezone: America/New_York
                    label: New York

            - type: calendar
              first-day-of-week: monday

            - type: weather
              location: Taipei, Taiwan
              units: metric
              hour-format: 12h

