- name: Reddit
  columns:
      - size: full
        widgets:
            - type: group
              widgets:
                  - type: reddit
                    cache: 10m
                    subreddit: Frontend
                    show-thumbnails: true
                    collapse-after: 10
                    limit: 20
                    show-flairs: true

                  - type: reddit
                    cache: 10m
                    subreddit: apexlegends
                    show-thumbnails: true
                    collapse-after: 10
                    limit: 20
                    show-flairs: true

                  - type: reddit
                    cache: 10m
                    subreddit: SonyAlpha
                    show-thumbnails: true
                    collapse-after: 10
                    limit: 20
                    show-flairs: true

                  - type: reddit
                    cache: 10m
                    subreddit: Steam
                    show-thumbnails: true
                    collapse-after: 10
                    limit: 20
                    show-flairs: true

                  - type: reddit
                    cache: 10m
                    subreddit: badminton
                    show-thumbnails: true
                    collapse-after: 10
                    limit: 20
                    show-flairs: true

