- name: Home
  columns:
      - size: small
        widgets:
            - type: calendar
              first-day-of-week: monday
            - type: twitch-channels
              channels:
                  - playapex
                  - nicewigg
                  - mande
                  - wannasinging
                  - scspple7545

      - size: full
        widgets:
            - type: group
              widgets:
                  - type: hacker-news
                    style: vertical-list
                    cache: 4h
                    limit: 25
                    collapse-after: 10
                  - type: rss
                    title: News
                    style: vertical-list
                    cache: 4h
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://news.pts.org.tw/xml/newsfeed.xml
                          title: 公視
                        - url: https://feeds.feedburner.com/rsscna/intworld
                          title: 中央通訊社 | 國際
                        - url: https://feeds.feedburner.com/rsscna/technology
                          title: 中央通訊社 | 科技
                        - url: https://feeds.feedburner.com/rsscna/sport
                          title: 中央通訊社 | 體育
                        - url: https://www.twreporter.org/a/rss2.xml
                          title: 報導者
                  - type: rss
                    title: English News
                    style: vertical-list
                    cache: 4h
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://feeds.bbci.co.uk/news/world/rss.xml
                          title: BBC News | World
                        - url: https://feeds.bbci.co.uk/news/rss.xml
                          title: BBC News | Top Stories
                  - type: rss
                    title: Games
                    style: vertical-list
                    cache: 4h
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://www.4gamers.com.tw/rss/latest-news
                          title: 4gamers
                        - url: https://gnn.gamer.com.tw/rss.xml
                          title: 巴哈姆特 GNN 新聞網
                        - url: https://store.steampowered.com/feeds/news.xml
                          title: steam news
                  - type: rss
                    title: Tech
                    style: vertical-list
                    cache: 4h
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://web.dev/static/blog/feed.xml
                          title: web.dev
                        - url: https://dev.to/feed
                          title: dev.to
                        - url: https://www.freecodecamp.org/news/rss
                          title: freeCodeCamp
                        - url: https://css-tricks.com/feed/
                          title: css-tricks
                    # - type: reddit
                    #   cache: 1h
                    #   subreddit: apexlegends
                    #   show-thumbnails: true

                    # - type: reddit
                    #   cache: 1h
                    #   subreddit: Frontend
                    #   show-thumbnails: true

                    # - type: reddit
                    #   cache: 1h
                    #   subreddit: SonyAlpha
                    #   show-thumbnails: true

                    # - type: reddit
                    #   cache: 1h
                    #   subreddit: Steam
                    #   show-thumbnails: true

                    # - type: reddit
                    #   cache: 1h
                    #   subreddit: badminton
                    #   show-thumbnails: true

            - type: videos
              style: horizontal-cards
              channels:
                  - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                  - UCsBjURrPoezykLs9EqgamOA # Fireship
                  - UCyU5wkjgQYGRB0hIHMwm2Sg # Syntax

      - size: small
        widgets:
            - type: weather
              location: Taipei, Taiwan
              units: metric
              hour-format: 12h
            - $include: widget/widget-word-of-the-day.yml
            - type: markets
              title: Global markets
              markets:
                  - symbol: SPY
                    name: S&P 500
                  - symbol: VT
                    name: VT
                  - symbol: QQQ
                    name: QQQ
                  - symbol: NVDA
                    name: NVIDIA
                  - symbol: AAPL
                    name: Apple
                  - symbol: NET
                    name: Cloudflare

            - type: markets
              title: Taiwan markets
              markets:
                  - symbol: 0050.TW
                    name: 0050
                  - symbol: 006208.TW
                    name: 006208
                  - symbol: 0056.TW
                    name: 0056

