- name: Start Page
  columns:
      - size: small
        widgets:
            - type: custom-api
              title: Word of the day
              cache: 1h
              url: https://api.wordnik.com/v4/words.json/wordOfTheDay?api_key=${WORDNIK_API_KEY}
              template: |
                  <div>
                    <div class="size-h2 color-primary">{{ .JSON.String "word" }}</div>
                    <div class="margin-bottom-5 size-h5" style="opacity:0.5">{{ .JSON.String "note" }}</div>

                    <ul class="list list-gap-4 margin-bottom-15">
                      {{ range .JSON.Array "definitions" }}
                        <li>
                          <ul>
                            <li>{{ .String "partOfSpeech" }}</li>
                            <li style="margin-left: 8px; padding-left: 8px;border-left: 1px solid var(--color-separator)">{{ .String "text" }}</li>
                          </ul>
                        </li>
                      {{ end }}
                    </ul>

                    {{ with .JSON.Array "examples" }}
                      {{ if gt (len .) 0 }}
                        <div class="size-h5 color-highlight margin-bottom-7">Examples:</div>

                        <ul class="list list-gap-10 collapsible-container" data-collapse-after="1">
                          {{ range . }}
                            <li>
                              <p class="margin-bottom-5">{{ .String "text" }}</p>
                              <a href='{{ .String "url" }}' target="_blank" class="visited-indicator text-truncate block size-h6" rel="noreferrer" title='{{ .String "title" }}'>Source</a>
                            </li>
                          {{ end }}
                        </ul>
                      {{ end }}
                    {{ end }}

                    <hr class="margin-bottom-10"/>
                    
                    <div class="flex justify-between items-center">
                      <a href='https://www.google.com/search?q=definition+{{ .JSON.String "word" }}' class="visited-indicator flex items-center gap-7 size-h6"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M9.5 16q-2.725 0-4.612-1.888T3 9.5t1.888-4.612T9.5 3t4.613 1.888T16 9.5q0 1.1-.35 2.075T14.7 13.3l5.6 5.6q.275.275.275.7t-.275.7t-.7.275t-.7-.275l-5.6-5.6q-.75.6-1.725.95T9.5 16m0-2q1.875 0 3.188-1.312T14 9.5t-1.312-3.187T9.5 5T6.313 6.313T5 9.5t1.313 3.188T9.5 14"/></svg><span>Search on Internet</span></a>
                      <p class="text-right size-h6">{{ .JSON.String "pdd" }}</p>
                    </div>
                  </div>
            - type: bookmarks
              groups:
                  - title: Quick Links
                    links:
                        - title: YouTube
                          url: https://www.youtube.com/
                          icon: di:youtube
                        - title: Twitch
                          url: https://www.twitch.tv/
                          icon: di:twitch
                        - title: Gmail
                          url: https://mail.google.com/mail/u/0/
                          icon: di:gmail
                        - title: Google Maps
                          url: https://www.google.com/maps
                          icon: di:google-maps
                        - title: Google Calendar
                          url: https://calendar.google.com/calendar/u/0/r
                          icon: di:google-calendar
                        - title: Perplexity
                          url: https://www.perplexity.ai/
                          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/perplexity-dark.svg
                        - title: Claude
                          url: https://claude.ai/
                          icon: di:claude-ai
                  - title: Entertainment
                    color: 10 70 50
                    links:
                        - title: YouTube
                          url: https://www.youtube.com/
                          icon: di:youtube
                        - title: Reddit
                          url: https://www.reddit.com/
                          icon: di:reddit
                        - title: Hyread
                          url: https://ebook.hyread.com.tw/
                        - title: Geocache
                          url: https://www.geocaching.com/play/search
                  - title: Work
                    color: 86 75 60
                    links:
                        - title: Github Repos
                          url: https://github.com/kevinshu1995?tab=repositories
                          icon: di:github-light
                        - title: Cloudflare
                          url: https://www.cloudflare.com/
                          icon: di:cloudflare
                        - title: Zeabur
                          url: https://zeabur.com/projects
                          icon: https://unpkg.com/@lobehub/icons-static-svg@latest/icons/zeabur.svg
                        - title: Vercel
                          url: https://vercel.com/login
                  - title: Study
                    color: 200 50 50
                    links:
                        - title: Spanish Dictionary
                          url: https://www.spanishdict.com/
                        - title: English News in Levels
                          url: https://englishnewsinlevels.com/
                        - title: Frontend Masters
                          url: https://frontendmasters.com/
                        - title: Vue Mastery
                          url: https://www.vuemastery.com/courses/
      - size: full
        widgets:
            - type: search
              search-engine: google
              autofocus: true
              target: _self
              bangs:
                  - title: YouTube
                    shortcut: "!yt"
                    url: https://www.youtube.com/results?search_query={QUERY}
                  - title: YouTube
                    shortcut: "!pp"
                    url: https://www.perplexity.ai/search?q={QUERY}
            - type: group
              widgets:
                  - type: hacker-news
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                  - type: rss
                    title: News
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://news.pts.org.tw/xml/newsfeed.xml
                          title: 公視
                        - url: https://feeds.feedburner.com/rsscna/intworld
                          title: 中央通訊社 | 國際
                        - url: https://feeds.feedburner.com/rsscna/technology
                          title: 中央通訊社 | 科技
                        - url: https://feeds.feedburner.com/rsscna/sport
                          title: 中央通訊社 | 體育
                        - url: https://www.twreporter.org/a/rss2.xml
                          title: 報導者
                  - type: rss
                    title: English News
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://feeds.bbci.co.uk/news/world/rss.xml
                          title: BBC News | World
                        - url: https://feeds.bbci.co.uk/news/rss.xml
                          title: BBC News | Top Stories
                  - type: rss
                    title: Games
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://www.4gamers.com.tw/rss/latest-news
                          title: 4gamers
                        - url: https://gnn.gamer.com.tw/rss.xml
                          title: 巴哈姆特 GNN 新聞網
                        - url: https://store.steampowered.com/feeds/news.xml
                          title: steam news
                  - type: rss
                    title: Tech
                    style: vertical-list
                    cache: 30m
                    limit: 25
                    collapse-after: 10
                    feeds:
                        - url: https://web.dev/static/blog/feed.xml
                          title: web.dev
                        - url: https://dev.to/feed
                          title: dev.to
                        - url: https://www.freecodecamp.org/news/rss
                          title: freeCodeCamp
                        - url: https://css-tricks.com/feed/
                          title: css-tricks
      - size: small
        widgets:
            - type: clock
              hour-format: 24h
              timezones:
                  - timezone: Europe/Paris
                    label: Paris
                  - timezone: America/New_York
                    label: New York

            - type: calendar
              first-day-of-week: monday

            - type: weather
              location: Taipei, Taiwan
              units: metric
              hour-format: 12h
