# Homepage Settings

title: My Services
subtitle: Personal Dashboard
language: en
theme: dark

layout:
    - name: Shortcuts
      icon: fas fa-stream

    - name: Services
      icon: fas fa-cloud

hideVersion: false

