# Homepage Widgets Configuration
- resources:
      cpu: true
      memory: true
      cputemp: true
      tempmin: 0 # optional, minimum cpu temp
      tempmax: 100 # optional, maximum cpu temp
      uptime: true
      units: metric # only used by cpu temp, options: 'imperial' or 'metric'
      refresh: 3000 # optional, in ms
      diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
      network: true # optional, uses 'default' if true or specify a network interface name

- datetime:
      text_size: xl
      format:
          dateStyle: medium
          timeStyle: short

